### ISSUE TITLE
mapping over list to create seq of ProduceRecord doesn't map with correct types 

### ISSUE THREAD

**Issue by 123avi** [cakesolutions/scala-kafka-client#101]
```
 val topics = List("topic1", "topic2")
 val batch: Seq[ProducerRecord[String, String]] = topics.map( t =>
      KafkaProducerRecord(t, "bar"))
```
resulting the wrong type 

> Error:(38, 64) type mismatch;
>  found   : List[org.apache.kafka.clients.producer.ProducerRecord[Nothing,String]]
>  required: Seq[org.apache.kafka.clients.producer.ProducerRecord[String,String]]
>     val batch: Seq[ProducerRecord[String, String]] = topics.map( t =>

but using other factory (by adding empty string) seems to work :
```
val topics = List("topic1", "topic2")
 val batch: Seq[ProducerRecord[String, String]] = topics.map( t =>
      KafkaProducerRecord(t, "", "bar"))

```

**Comment by jkpl** [comment]
The `KafkaProducerRecord` constructor that doesn't specify the key infers the key type to be `Nothing` by default. Can you try calling it like this: `KafkaProducerRecord[String, String](t, "bar")`

**Comment by jkpl** [comment]
I'll have to check this to be correct, but my intuition tells me that the reason why the inferred record doesn't work there is because the `ProducerRecord` is a Java type. Therefore it doesn't support the same variance rules as what Scala provides.

**Comment by 123avi** [comment]
Yes, I see what you mean thanks.
looking at the apply method  
`def apply[Key, Value](topic: String, value: Value): ProducerRecord[Key, Value] 
`
omitting the Key default to Nothing
