### ISSUE TITLE
Received confirmation for unexpected offsets

### ISSUE THREAD

**Issue by 123avi** [cakesolutions/scala-kafka-client#102]
I see this sort of messages a lot in log after I send the confirm message.

> 
> [WARN] [03/03/2017 22:53:55.390] [MyActorSystem-akka.actor.default-dispatcher-5] [akka://MyActorSystem/user/pingActor/PingKafkaConsumerActor] Received confirmation for unexpected offsets: Offsets(pong-0 = 18000)
> [INFO] [03/03/2017 22:53:55.390] [MyActorSystem-akka.actor.default-dispatcher-10] [akka://MyActorSystem/user/pingActor] In PongActor - id:e6a, msg: PingPongMessage(pong), offsets Offsets(pong-0 = 18000)
> [INFO] [03/03/2017 22:53:55.390] [MyActorSystem-akka.actor.default-dispatcher-10] [akka://MyActorSystem/user/pingActor] In PongActor - id:K7V, msg: PingPongMessage(pong), offsets Offsets(pong-0 = 18000)
> ...
 this is the configuration that I use : 
```
val config: Config = ConfigFactory.parseString(
    s"""
       | bootstrap.servers = "localhost:9092",
       | group.id = "$randomString"
       | enable.auto.commit = false
       | auto.offset.reset = "earliest"
       | schedule.interval = 1 second
       | unconfirmed.timeout = 3 seconds
       | max.redeliveries = 3
        """.stripMargin
  )
```
how can I fix it ?

**Comment by 123avi** [comment]
This is the configuration that I am using :
```
  val config: Config = ConfigFactory.parseString(
    s"""
       | bootstrap.servers = "localhost:9092",
       | group.id = "$randomString"
       | enable.auto.commit = false
       | auto.offset.reset = "earliest"
       | schedule.interval = 1 second
       | unconfirmed.timeout = 3 seconds
       | max.redeliveries = 3
        """.stripMargin
  )

```

**Comment by jkpl** [comment]
Can you show the code for sending the confirmation message?

**Comment by 123avi** [comment]
it seems to bb that something went wrong in the way. so I cleaned everything and reset my environment and it seems to be ok now
