### ISSUE TITLE
Cannot find version 0.10.1.2

### ISSUE THREAD

**Issue by anicolaspp** [cakesolutions/scala-kafka-client#103]
For some reason we lost the ability to see version `0.10.1.2`

**Comment by jkpl** [comment]
Where are you getting your dependencies from? Bintray?

**Comment by anicolaspp** [comment]
yes, we were using `0.10.1.2` few day ago, we cannot see it any longer. We just updated to `0.10.2.0` so does not matter anyways

**Comment by jkpl** [comment]
Weird. [Bintray only lists availability for 2.12](https://bintray.com/cakesolutions/maven/scala-kafka-client/0.10.1.2) for that version, but the [file directory contains the JARs](https://bintray.com/cakesolutions/maven/scala-kafka-client/0.10.1.2#files/net/cakesolutions/scala-kafka-client_2.11/0.10.1.2).
