### ISSUE TITLE
How this work compare to Kafka Connect vs Comsumer and Producer

### ISSUE THREAD

**Issue by Maatary** [cakesolutions/scala-kafka-client#106]
I wonder if this work is some sort of Kafka Connect or the Consumer/Producer API, or something in between. I know that connect simplify a lot of things with respect to the Consumer/Producer API. Where would that work fit ?

**Comment by simonsouter** [comment]
Its not really that similar to kafka connect.  See here for a description: https://github.com/cakesolutions/scala-kafka-client/wiki/Akka-Integration
