### ISSUE TITLE
Getting exception of fast load

### ISSUE THREAD

**Issue by 123avi** [cakesolutions/scala-kafka-client#108]
I am trying to publish 100K messages to kafka however after a while I am getting this errors:
```
org.apache.kafka.common.errors.TimeoutException: Expiring 69 record(s) for mytopic-0 due to 30001 ms has passed since batch creation plus linger time
484305-19:11:04.002 [foo-akka.actor.default-dispatcher-2] ERROR c.kafka.akka.KafkaProducerActor - Failed to send message to Kafka!

```
And this one

```
625596:org.apache.kafka.common.errors.TimeoutException: Expiring 69 record(s) for mytopic-0 due to 30026 ms has passed since last append
625597-19:11:12.350 [foo-akka.actor.default-dispatcher-6] ERROR c.kafka.akka.KafkaProducerActor - Failed to send message to Kafka!
```

**Comment by simonsouter** [comment]
This sounds like its related to the underlying behaviour of the Kafka driver.  Have a look at these posts: http://stackoverflow.com/questions/34794260/when-does-the-apache-kafka-client-throw-a-batch-expired-exception and http://stackoverflow.com/questions/41564051/getting-errorbatch-containing-3-records-expired-due-to-timeout-while-requesti

**Comment by 123avi** [comment]
Thanks, I'll check it
