### ISSUE TITLE
Create a source release

### ISSUE THREAD

**Issue by danbim** [cakesolutions/scala-kafka-client#112]
It would be great if you released a source artifact so a users IDE can automatically download it :)

**Comment by simonsouter** [comment]
Sources appear to be published, see here: https://bintray.com/cakesolutions/maven/scala-kafka-client#files/net/cakesolutions/scala-kafka-client_2.12/0.10.2.1

**Comment by danbim** [comment]
Oh, sh* sorry, seems to be an IntelliJ issue. Weirdly it works for all my other dependencies. Thx anyway!
