### ISSUE TITLE
Fail to cast while using ConsumerRecords.extractor[Long,String]

### ISSUE THREAD

**Issue by lujiajing1126** [cakesolutions/scala-kafka-client#116]
I used `private val extractor = ConsumerRecords.extractor[Long,String]` as an extractor, but I failed to get any message.

If changing to `ConsumerRecords.extractor[String,String]`, it worked.

I found that the `hasType[Other: TypeTag]` method in` TypeTaggedTrait` trait returned false while not having String as key. It's very strange.

Anyone has this problem?

**Comment by lujiajing1126** [comment]
Oh, I see

Scala will not automatically convert `Long` to `java.lang.Long` while it appear in the Collection and etc.

So I should there must be a fix for that

**Comment by simonsouter** [comment]
If your key is a java.lang.Long, maybe all you need is:

private val extractor = ConsumerRecords.extractor[java.lang.Long,String]
