### ISSUE TITLE
example of consumer to receiver messaging

### ISSUE THREAD

**Issue by meatware** [cakesolutions/scala-kafka-client#121]
Hi, I'm still pretty new to Scala and am trying to get the cakesolutions akka client up and running. 
I think I have got my (very) rough implementation connected to kafka, but am puzzled as to how to pass messages between consumer <--> receiver. My code is below. 

I would be very grateful if anyone could possibly give me any pointers or examples on how to get consumer and receiver actors talking?

```
object eatKafka extends App {

  println("\n\n\n")
  // Create an Akka system
  println("\n\ncreating system...")
  val system = ActorSystem("VySystem")

  // create receiver
  println("\n\ncreating receiver...")
  val receiver = system.actorOf(Props[ReceiverActor], name = "receiver")

  // create cake kafka consumer
  println("\n\ncreating consumer...")
  val conf = ConfigFactory.load()

  //Construct the KafkaConsumerActor with Typesafe config in resources
  val cakeKConsumer = system.actorOf(
    KafkaConsumerActor.props(conf, new ByteArrayDeserializer(), new ByteArrayDeserializer(), receiver)
  )

  println("pass subscription details to cakeKConsumer")
  cakeKConsumer ! Subscribe.AutoPartition(List("impression")) //Subscribe.ManualOffset(Offsets(Map((new TopicPartition("impression", 0), 1))))

}


/////////////////////////////////////////////////////////////////////
// kafka consumer actor
class kConsumeCakeActor extends Actor {
  // https://github.com/cakesolutions/scala-kafka-client/blob/master/akka/src/main/scala/cakesolutions/kafka/akka/KafkaConsumerActor.scala
  println("\n\nIn consumer!!")
  override def receive = {
    case default => println("I am kConsumeCakeActor")
  }
}


/////////////////////////////////////////////////////////////////////
// receiver actor
class ReceiverActor extends Actor {
  // Extractor for ensuring type safe cast of records
  val recordsExt = ConsumerRecords.extractor[Int, ByteString]
  println("In receiver")
  override def receive: Receive = {
    case recordsExt(records) =>
      println("do something with records")
      //for (record <- records) println(record)
      sender() ! Confirm(records.offsets)

    case default => println("I am receiver!!")
  }
}
``` 

Sample output:
```
[info] Running eatKafka 
[info] 
[info] 
[info] 
[info] 
[info] 
[info] 
[info] creating system...
[info] 
[info] 
[info] creating receiver...
[info] 
[info] 
[info] creating consumer...
[info] In receiver
[info] pass subscription details to cakeKConsumer

[info] [INFO] [08/24/2017 09:33:20.853] [VySystem-akka.actor.default-dispatcher-3] [akka://VySystem/user/$a] Subscribing in auto partition assignment mode to topics [impression].
[info] I am receiver!!
[info] [INFO] [08/24/2017 09:33:31.493] [VySystem-akka.actor.default-dispatcher-3] [akka://VySystem/user/$a] In bufferFull: records timed out while waiting for a confirmation.
[info] [INFO] [08/24/2017 09:33:31.493] [VySystem-akka.actor.default-dispatcher-3] [akka://VySystem/user/$a] In bufferFull: redelivering.
[info] I am receiver!!
[info] I am receiver!!
```

**Comment by simonsouter** [comment]
You are creating a KafkaConsumer actor with key type: ByteArray and value type ByteArray, but in your receiver actor you are matching key type: Int, value: ByteArray (ConsumerRecords.extractor[Int, ByteString]).  That is probably why its not matching the results.

Here is a working example of what you are trying to do: https://github.com/cakesolutions/scala-kafka-client/blob/master/examples/src/main/scala/cakesolutions/kafka/examples/ConsumerToProducer.scala

**Comment by meatware** [comment]
Thanks very much Simon. That's sorted it. The key was unset, so my experiments with null, etc were failing. the key was an empty Array[byte]. So the correct line was: 

val recordsExt = ConsumerRecords.extractor[Array[Byte], Array[Byte]]

**Comment by meatware** [comment]
Just a quick question: Is it not advisable to use the cakesolutions scala-kafka-client-akka with a downstream worker router as demonstrated in the example pi calculation tutorial:

http://doc.akka.io/docs/akka/2.0.1/intro/getting-started-first-scala.html

**Comment by simonsouter** [comment]
Thats not usually a great idea, as kafka sends records in a batch to the receiver and they should be confirmed once all records are processed.  If you 'fan out' the messages to a number of workers, it is can be tricky if one of the workers fails.  Also message ordering is lost.

If you want to parralelise the processing of a topic, it is preferable to create multiple kafkaconsumers+receivers with the same groupId, and use Kafka's natural partitioning.

**Comment by meatware** [comment]
Many thanks for the info. Does Kafka Streams fanning out handle this better?
