### ISSUE TITLE
scala-kafka-client for scala 2.11 in bintray

### ISSUE THREAD

**Issue by bilyush** [cakesolutions/scala-kafka-client#128]
Hi there, 

Do you have any plans to release version `1.0.0` for scala `2.11` ? It seems like bintray doesn't have appropriate artifacts:
https://dl.bintray.com/cakesolutions/maven/net/cakesolutions/scala-kafka-client_2.11/

Cheers,
Boris

**Comment by simondumas** [comment]
Hello,

Same thing here, we are stuck on 2.11 because of spark stuff...
So it would be great if you could release 1.0.0 for scala 2.11 :).

Thanks,
Simon

**Comment by ri-boris** [comment]
@ simonsouter, could you share some light on the issue?

**Comment by simonsouter** [comment]
Had an issue building latest against 2.11 .  Bit had a chance to resolve
this yet.  I would suggest to use the previous release and override the
Kafka dependency to 1.0.0 for now.

**Comment by ri-boris** [comment]
@simonsouter , thanks for quick reply. I tried to compile master under 2.11 and it worked :). Could I help some how with the issue you found?

**Comment by simonsouter** [comment]
Ok pushed now.  Had a dodgy binary in local cache... Sorry for the delay.
