### ISSUE TITLE
Typo in https://github.com/cakesolutions/scala-kafka-client/wiki/KafkaConsumerActor-Configuration

### ISSUE THREAD

**Issue by shafiquejamal** [cakesolutions/scala-kafka-client#138]
In https://github.com/cakesolutions/scala-kafka-client/wiki/KafkaConsumerActor-Configuration

`  def processRecords(records: org.apache.kafka.clients.consumer.ConsumerRecords[String, String]) = { ... }`

should instead be

`  def processRecords(records: org.apache.kafka.clients.consumer.ConsumerRecords[Int, String]) = { ... }`

**Comment by simonsouter** [comment]
Updated, cheers
