### ISSUE TITLE
Error in https://github.com/cakesolutions/scala-kafka-client/wiki/KafkaConsumerActor-Configuration

### ISSUE THREAD

**Issue by shafiquejamal** [cakesolutions/scala-kafka-client#139]
In https://github.com/cakesolutions/scala-kafka-client/wiki/KafkaConsumerActor-Configuration

The type information for the named arguments should not be there, e.g.

`autoCommitInterval: Int = 1000,`

should instead be:

`autoCommitInterval = 1000,`

(likewise for the arguments that follow... at least for Scala 2.11.11)

**Comment by simonsouter** [comment]
Updated, cheers

**Comment by simonsouter** [comment]
Updated, cheers
