### ISSUE TITLE
Wiki typos

### ISSUE THREAD

**Issue by niqdev** [cakesolutions/scala-kafka-client#147]
Hi,

in the Consumer [wiki](https://github.com/cakesolutions/scala-kafka-client/wiki/Scala-Kafka-Client#direct-configuration-1) this snippet doesn't compile

```scala
val consumer = KafkaConsumer(
    Conf(new StringDeserializer(), new StringDeserializer(), bootstrapServers = "localhost:9092")
)
```

because `groupId` is missing

```scala
val consumer = KafkaConsumer(
    Conf(new StringDeserializer(), new StringDeserializer(), bootstrapServers = "localhost:9092", groupId = "group")
  )
```

and the Testkit [wiki](https://github.com/cakesolutions/scala-kafka-client/wiki/Testkit#resolve), probably due to a bad space, is not properly formatted

![testkit](https://user-images.githubusercontent.com/9458643/48061346-836c2400-e1b6-11e8-9460-85a6930a881d.png)

In the client [test](https://github.com/cakesolutions/scala-kafka-client/blob/master/client/src/test/scala/cakesolutions/kafka/KafkaConsumerSpec.scala) your are not using `kafkaServer.produce` and `kafkaServer.consume` for example [here](https://github.com/cakesolutions/scala-kafka-client/blob/master/client/src/test/scala/cakesolutions/kafka/KafkaConsumerSpec.scala#L39), is there a specific reason?

I've had also issues consuming using the recommended

`public ConsumerRecords<K, V> poll(final Duration timeout)`

while it works fine with with the `@Deprecated` [`consumer.poll`](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L1122) as you did in your example, have you experienced similar problem?

I'm currently working on a presentation and I created few [examples](https://github.com/niqdev/kafka-demo#kafka) with your library.

Thanks

**Comment by simonsouter** [comment]
Thanks ill update this, thanks.

**Comment by simonsouter** [comment]
Updated
