### ISSUE TITLE
client rediness for kafka 2.1.0

### ISSUE THREAD

**Issue by mtekp** [cakesolutions/scala-kafka-client#148]
Kafka 2.1.0 is released 15 days back. And the client needs to be tested and certified for latest kakfa 2.1.0

**Comment by simonsouter** [comment]
Released https://github.com/cakesolutions/scala-kafka-client/releases/tag/v2.1.0
Cheers

**Comment by francescopellegrini** [comment]
You forgot to update README header and repo description.
