### ISSUE TITLE
Cached commit offsets can become stale and cause record replay after group rebalance

### ISSUE THREAD

**Issue by ctoomey** [cakesolutions/scala-kafka-client#157]
Thanks for this useful library.

We're using the Akka actor consumer for a consumer group comprised of 6 servers consuming from a 3-partition topic in auto-commit mode. and were having a mysterious problem after rolling consumer restarts: sometimes 1 or more of the consumers would start re-consuming old records from their partition. After digging through the logs we found a smoking gun:

```
2020-02-06 22:11:30.912 - - INFO c.k.a.TrackPartitionsCommitMode .. Seeking partition: [mytopic-0] to offset [94143]
2020-02-06 22:11:30.912 - - INFO c.k.a.TrackPartitionsCommitMode .. Seeking partition: [mytopic-1] to offset [94158]
2020-02-06 22:11:30.912 - - INFO c.k.a.TrackPartitionsCommitMode .. Seeking partition: [mytopic-2] to offset [74342]
```

Each of the partitions have approximately the same number of records and the consumers are generally caught up, but as we see above after the rebalance the partition 2 consumer was told to start consuming ~20k records back in the history (offset 74k instead of 94k).

Looking into how `TrackPartitionsCommitMode` handles rebalancing (partition revocation and assignment), I found the problem: the optimization it attempts to do for cases when the consumer is re-assigned the same partitions -- wherein it locally caches the current offsets upon revocation and restores them via seek after assignment -- fails to clear the cache in the case the revoked partition set is empty. Thus if a consumer owns a given set of partitions, then rebalancing hands it an empty set of partitions, then a later rebalance hands it the original set of partitions again, it tells the client to seek to the stale cached offsets and resume from there. In our case the cached offsets were almost a week old which is how they were 20k records behind.

It's an easy fix, but the larger question for me is whether this attempted optimization even achieves anything in the happy path? From what I can tell in that case it just asks Kafka for the current offsets upon revocation, then tells it to seek to those after assignment, which is what Kafka would have done anyway in auto-parition mode. How is it any different or what does it yield in savings? 

Given this in the upcoming PR I've provided both a fix to `TrackPartitionsCommitMode` and a variant `TrackPartitionsCommitModeBasic` which does away w/ the whole caching business.

**Comment by simonsouter** [comment]
It's been a while since i coded this, but i think the main purpose of this optimisation was to prevent repartitions causing unnecessary message redeliveries.  The Kafka driver is designed for synchronous polling from a single thread, which doesn't play well with our approach of using multiple threads.
