### ISSUE TITLE
There is no case class Records

### ISSUE THREAD

**Issue by gabrielgiussi** [cakesolutions/scala-kafka-client#28]
There is no [case class Records](https://github.com/cakesolutions/scala-kafka-client/wiki/Akka-Kafka-Client#recordsk-v) in KafkaConsumerActor.

    import cakesolutions.kafka.akka.KafkaConsumerActor.{Confirm, Records} // Records not found

    class ReceiverActor extends Actor {

      override def receive:Receive = {
      case r:Records[_, _] =>

      //Type safe cast of records to correct serialisation type
      r.cast[String, String] match {
        case Some(records) =>
          processRecords(records.records)
          sender() ! Confirm(r.offsets)
        case None => log.warning("Received wrong Kafka records type!")
      }
  }

I'm using "net.cakesolutions" %% "scala-kafka-client-akka" % "0.7.0",

**Comment by jkpl** [comment]
Hi, thanks for reporting the issue! The docs were out of sync with the implementation. I updated the wiki page. Let me know if you have anymore issues. :-)
