### ISSUE TITLE
Not an issue, but a question about where to catch 'java.net.ConnectException'?

### ISSUE THREAD

**Issue by skedin** [cakesolutions/scala-kafka-client#39]
Ex: I have a piece of code:
```
val kafkaConsumer = system.actorOf(
    KafkaConsumerActor.props(
        KafkaConsumer.Conf(config.getConfig("kafka"), new StringDeserializer, new StringDeserializer),
        KafkaConsumerActor.Conf(config.getConfig("kafka-actor")),
        kafkaService
    )
)
kafkaConsumer ! Subscribe()
```

If Kafka server is not started yet, where to catch java.net.ConnectException?
I surround the piece of code above by try catch, but I did not catch the exception.

**Comment by simonsouter** [comment]
Try/Catch is not the mechanism used to determine if a connection error has occurred.  The KafkaConsumerActor will make a best-effort to connect to Kafka, with an internal retry mechanism (that is configurable).  Should it fail, it propagates an exception via the [Supervision mechanism](http://doc.akka.io/docs/akka/snapshot/scala/fault-tolerance.html).

I will raise a ticket to improve the documentation around error handling...

**Comment by skedin** [comment]
Does it mean I must create an Actor to create a child KafkaConsumerActor, and I override supervisorStrategy in my Actor? If I would like to create KafkaConsumerActor in my main App, how to handle the fault?

Thanks

**Comment by simonsouter** [comment]
You are going to need at least another Actor to receive/ process messages from the KafkaConsumerActor anyway (presumably the "kafkaService" in your snippet).  That actor can also double as the supervisor.  If you want to consume directly in the App, you can consider using the KafkaConsumer helper class (or the Java driver directly), although you won't benefit from the non blocking capability of the Actor.

**Comment by jkpl** [comment]
Besides [tuning the actor supervisor strategy](), you can also tune [the actor system supervisor strategy](http://doc.akka.io/docs/akka/2.4.7/general/configuration.html#Listing_of_the_Reference_Configuration) (see `guardian-supevisor-strategy`).
