### ISSUE TITLE
kafka rebalance listner

### ISSUE THREAD

**Issue by mazorigal** [cakesolutions/scala-kafka-client#52]
Hi,

is there option to add custom ConsumerRebalanceListener with the subscription to a topic ?

Thanks

**Comment by simonsouter** [comment]
If you are referring to the KafkaConsumerActor, then not currently.  We have considered some kind of hook to do this for a very specific use case.  What is the use case you are considering?

**Comment by mazorigal** [comment]
to use it with manual commit to external storage.

from kafka docs:

"""In addition, when group reassignment happens automatically, consumers can be notified through ConsumerRebalanceListener, which allows them to finish necessary application-level logic such as state cleanup, manual offset commits (note that offsets are always committed for a given consumer group), etc. See Storing Offsets Outside Kafka for more details"""

https://kafka.apache.org/090/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html

**Comment by simonsouter** [comment]
Hi,

Indeed this use case isn't supported right now.  Specifically using self managed offsets with auto partition assignment.  We are considering adding support for this use case (by propagating partition assignment changes back to the user).

One use case we will be supporting shortly (next release, coming soon) is using self managed offsets with Manual Partition assignment.

**Comment by mazorigal** [comment]
great, looking forward for the new release :-)
