### ISSUE TITLE
kafka auto.offset.reset earliest not working

### ISSUE THREAD

**Issue by mazorigal** [cakesolutions/scala-kafka-client#58]
Hi,

I was using the auto.offset.reset "earliest" strategy, and when started a consumer with new group.id, which subscribed to already existing topics (with LOG-END-OFFSET > 0 for topics partitions),
The consumer was not able to pull any data from kafka.
using kafka-consumer-groups.sh the output was

GROUP    TOPIC    PARTITION    CURRENT-OFFSET    LOG-END-OFFSET    LAG    OWNER
my-group      test-topic    0          unknown         197             unknown         client123_/192.168.99.1

just to verify, I tried also using ./kafka-console-consumer.sh with --from-beginning flag, and that was fine.

Thanks,

**Comment by jkpl** [comment]
How are you setting the configuration and how are you subscribing?

**Comment by mazorigal** [comment]
I have application.conf file in resources folder

this is part of the config:

```
akka {
    kafka.consumer {
    kafka-clients {
      bootstrap.servers = "192.168.99.100:9092"
      bootstrap.servers = ${?KAFKA_SERVERS}
      group.id = "product-profile-builder"
      auto.offset.reset = "latest"
      enable.auto.commit = false
      max.poll.records = 20
    }
  }
}
```

and subscribe is simply like in your examples

```
private val kafkaConsumerActor = context.actorOf(
    KafkaConsumerActor.props(
      consumerConf = KafkaConsumer.Conf(
        config.withValue("client.id", ConfigValueFactory.fromAnyRef(clientID)),
        keyDeserializer = new StringDeserializer,
        valueDeserializer = new StringDeserializer
      ),
      actorConf = actorConf,
      self
    ),
    "KafkaConsumer"
  )

override def preStart() = {
    super.preStart()
    kafkaConsumerActor ! Subscribe()
  }
```

config: Config is part of the receiving actor init params 
and that is how I load it

```
Try(ConfigFactory.load().getConfig("akka.kafka.consumer.kafka-clients")) match {
    case Success(c) => c
    case Failure(e) =>
      terminate("unable to load consumer config")
  }
```

**Comment by jkpl** [comment]
What version of scala-kafka-client are you using? By the way, if you have committed offsets to the topic, the consumers will start consuming from the last commit even with `auto.offset.reset` = "earliest".

**Comment by mazorigal** [comment]
I am using 0.8.0

as far as I know, even if you commit offset to a topic with specific group.id, when you will consume from the same topic but using different group.id, for the first time it should act according to the selected auto.offset.reset strategy

**Comment by mazorigal** [comment]
just small update,

I have some more tests, and eventually deleted the problematic topic and recreated it.
For now all looks to work fine. Not sure where was the source of the problem.
Perhaps there was some issue during the topic offsets commit, process ended wrong, or some internal kafka bug.
Any way I will keep monitoring that, and in case I will encounter the issue again, will report.

Nevertheless will be great if you can also do some tests to verify that all works fine (at least from your kafka-client perspective)

Thanks,

**Comment by jkpl** [comment]
Thanks for the feedback. The problem could also come from the Java Kafka client we use inside our actors. We'll keep improving our test scenarios.
