### ISSUE TITLE
Convenient way to supply ValueDeserializer

### ISSUE THREAD

**Issue by janm399** [cakesolutions/scala-kafka-client#59]
It would be convenient to be able to supply the ``valueDeserializer`` as just a ``Array[Byte] => A``; this will be especially helpful for ScalaPB Protobuf generated code.

```
KafkaConsumer.Conf(
    ...,
    keyDeserializer = ...,
    valueDeserializer = Enveope.parseFrom
)
```

Where ``Enveope.parseFrom`` is ``def parseFrom(s: Array[Byte]): Enveope``.

**Comment by jkpl** [comment]
👍
