### ISSUE TITLE
Question: Could I use an Actor to subscribe multiple topics and also I can tell which topic the incoming message belongs to?

### ISSUE THREAD

**Issue by skedin** [cakesolutions/scala-kafka-client#66]
To subscribe multiple topics, currently I use multiple actors to handle multiple topics one by one. Is it possible to use only one actor and I also can tell which topic the message belongs to?

**Comment by jkpl** [comment]
Hi!

The `cakesolutions.kafka.akka.ConsumerRecords` that the `KafkaConsumerActor` sends to the receiver actor contains the Java client's [ConsumerRecords](http://kafka.apache.org/0100/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html). That API has methods for accessing records by topic.
