### ISSUE TITLE
log4j-over-slf4j dependency in client causes conflitcts in projects that use slf4j-log4j12 

### ISSUE THREAD

**Issue by dholbrook** [cakesolutions/scala-kafka-client#69]
The dependency conflict can be worked around by via sbt exclusion, but typically libraries leave the underlying slf4j adapters undefined for down stream projects.

**Comment by simonsouter** [comment]
Thanks for the observation, the current arrangement is indeed not ideal for log4j users.  We should change it as you have suggested.

**Comment by tharpa** [comment]
I've just run into this issue. When will be in the bintray repo?

**Comment by jkpl** [comment]
Hi, Simon's currently on a holiday. We'll make a release when he gets back.

**Comment by simonsouter** [comment]
Hi @tharpa, this fix is now released as 0.10.1.0
