### ISSUE TITLE
Consumer Actor could provide an Ack on Successful Subscription on Topics

### ISSUE THREAD

**Issue by psilos** [cakesolutions/scala-kafka-client#73]
Hello,

The current issue I'm facing at the moment is that upon instructing the Kafka Consumer to Subscribe on given Topics, there is no way to know if it has finished with the subscription or not. 

By following the example provide for the KafkaConsumerActor, we subscribe by sending:

```
 override def preStart() = {
    super.preStart()
    kafkaConsumerActor ! Subscribe()
  }
```

and we immediately return assuming it's consuming already. By relying on the default reset strategy, the consumer will start consuming from the latest offset. 

The issue arises if we start publishing messages on a topic straight after this Actor has been created and (instructed to) subscribe. There is a small window where messages are going to be skipped while the subscription is happening. 

Is there a way to acknowledge that the subscription has been completed? 

E.g. after it has transitioned from state unsubscribed -> ready ?

**Comment by jkpl** [comment]
Hiya, the actor currently doesn't give any feedback when the subscription has finished. It is possible to give send a message as a response when the subscription is done on the internal Java client, but I'm not sure if I can guarantee anything better.

Usually these problems are solved by using `earliest` as the offset reset strategy. This way the driver will automatically start from the beginning, if no commits have been done, and the message processor will encounter the messages already enqueued to the topic.

**Comment by psilos** [comment]
Hello,

Thank you for the quick feedback, I believe this initial ack of the subscription could be a good starting point. 

I'm afraid subscribing on the earliest is not always an option, most of the times the topic would have thousands of messages that we don't want to consume :) 

Or we just want to add a brand new consumer group that has nothing to do with the previous consumer groups.

**Comment by jkpl** [comment]
I made a PR (#74) as an experiment. It's not quite finished though.

Another interesting solution would be a timestamp based solution, which we could add a support for in the Kafka 0.10.1.0 compatible version. It allows querying offsets based on timestamps, thus we could use it as a subscription model: user could subscribe for topics starting from a given timestamp. In your case, the consumer could subscribe for all the messages starting from the app start time, and you wouldn't need to coordinate subscription and message producing.

**Comment by psilos** [comment]
Thank you very much for the initial fix. It seems good enough to me and will serve the purpose, that's what I had in mind pretty much.

This solution seems lightweight enough that doesn't affect the application, and it won't complicate it  unnecessarily. The intended usage of this fix would be to now subscribe like this:

`override def preStart() = {
super.preStart()
implicit val timeout = Timeout(1 seconds)
val future = kafkaConsumerActor ? Subscribe()
Await.result(future, timeout.duration)

// Check Result
}`

This will guarantee that Actor has been created and subscribed successfully before we start publishing. 

The only solution we have at the moment, is to sleep / wait for an arbitrary time.

Hope this makes sense

**Comment by psilos** [comment]
Hi @jkpl,

Any chance to merge the proposed solution? Or does it need to go through PR process first? 

Thanks

**Comment by simonsouter** [comment]
Hi @psilos Im not sure the proposed PR is really viable for your purpose.  We could deliver the successful subscription response to you once we have processed it, but we would not be able to guarantee that Kafka has actually established the subscription, which could take a while if there is rebalancing happening.

Its not really that easy to coordinate the consumer and producer in the way that you want with Kafka.  The only way I could imagine this is by subscribing with a specific Offset.

There is also a new feature in the Java Consumer to subscribe to a given timestamp, I am considering adding this feature to the KafkaConsumerActor.

Regards
