### ISSUE TITLE
Publish Scala 2.12.x compatible binaries

### ISSUE THREAD

**Issue by simonsouter** [cakesolutions/scala-kafka-client#75]
Currently this is on hold awaiting a Kafka release against Scala 2.12.

**Comment by yoks** [comment]
Looks like Kafka build against 2.12 is available
http://search.maven.org/#artifactdetails%7Corg.apache.kafka%7Ckafka_2.12%7C0.10.1.1%7Cjar
0.10.1.1 release.

**Comment by hseeberger** [comment]
+1

**Comment by hseeberger** [comment]
BTW, as this lib wraps the Java driver, why are you waiting for a Kafka release against 2.12?

**Comment by jkpl** [comment]
@hseeberger The testkit we provide depends on Kafka.

**Comment by hseeberger** [comment]
Thanks for the clarification!

**Comment by simonsouter** [comment]
Pushed out a new release 0.10.1.2 - crossbuilt against 2.11.8 and 2.12.1.

**Comment by hseeberger** [comment]
Wow, that was fast. Thanks!
