### ISSUE TITLE
KafkaConsumerActor should watch for downstream actor termination

### ISSUE THREAD

**Issue by yoks** [cakesolutions/scala-kafka-client#79]
`KafkaConsumerActor` created with `ActorRef` for the `downstreamActor` and in case if downstream actor terminates this `ActorRef` will no longer be valid, e.g. all messages will go to `DeadLetters`. 

At the moment there is no `DeathWatch` setup to monitor downstream actor lifecycle, and because KafkaConsumerActor do not supervise downstream actor, it will still try to deliver messages to dead actor.

I suggest to add watch(downstreamActor), in `KafkaConsumerActor` and terminate `KafkaConsumerActor` if `downstreamActor` terminates and close connection.

**Comment by yoks** [comment]
Also possible solutions can be:

- Use ActorSelection instead of ActorRef, but this will require stable path from the `downstreamActor`
- Make `downstreamActor` to be supervisor of the Consumer actor: `context.actorOf(KafkaConsumerActor.props(consumerConfig, actorConf, self))`

I still think initiating DeathWatch is best possible solution here which will not change API and will guard against possible connections leak.

**Comment by jkpl** [comment]
Thanks for your contribution! I'll have a think about these solutions.
