### ISSUE TITLE
Teskit log dependency error

### ISSUE THREAD

**Issue by dmartindelorme** [cakesolutions/scala-kafka-client#84]
Hi,

I am using the testkit latest version (0.10.1.2) but I have the following error when launching tests: 
`java.lang.NoClassDefFoundError: org/apache/log4j/Logger
at kafka.utils.Logging$class.logger(Logging.scala:24)
at kafka.server.KafkaServerStartable.logger$lzycompute(KafkaServerStartable.scala:32)
at kafka.server.KafkaServerStartable.logger(KafkaServerStartable.scala:32)
at kafka.utils.Logging$class.fatal(Logging.scala:118)
at kafka.server.KafkaServerStartable.fatal(KafkaServerStartable.scala:32)
at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:43)
at cakesolutions.kafka.testkit.KafkaServer.startup(KafkaServer.scala:113)`

My project is a Play application so I am using its logger and currently I have the following work-around in my build.sbt: `libraryDependencies += "org.slf4j" % "log4j-over-slf4j" % "1.7.22" % Test`
but then the KafkaServer class cannot log anything.

I also noticed that this error could be similar to https://github.com/cakesolutions/scala-kafka-client/issues/69 but I am not sure since the issue seems resolved.

Any ideas on how to fix it in the testkit ?

**Comment by simonsouter** [comment]
Hi,

Adding the log4j-over-slf4j dependency as you have done is the correct thing to do (i.e. its not a workaround).  That should route Kafka's log4j logs through Play's Logback logger.

Not sure what logging you are expecting from KafkaServer?

**Comment by dmartindelorme** [comment]
Thanks for the update, I was just missing a logger entry for "cakesolutions.kafka" in my logback.xml. Now I see KafkaServer's logs like this one for example:  [https://github.com/cakesolutions/scala-kafka-client/blob/v0.10.1.2/testkit/src/main/scala/cakesolutions.kafka/testkit/KafkaServer.scala#L114](https://github.com/cakesolutions/scala-kafka-client/blob/v0.10.1.2/testkit/src/main/scala/cakesolutions.kafka/testkit/KafkaServer.scala#L114).
