### ISSUE TITLE
Use of Kafka Server in the toolkit

### ISSUE THREAD

**Issue by dmartindelorme** [cakesolutions/scala-kafka-client#85]
Hi again,

Since there is very little documentation about the testkit, I'm really struggling with the use of KafkaServer.

First of all, I don't really know if I'm supposed to create a new KafkaServer for every test or if I can reuse the same server for all the tests in my suite ?

Second, I would prefer to re-use the same instance in all my tests in the Suite. But the problem is that the consume function reads every message from the log and not just those I have produced in the current test but also messages already consumed in previous tests. Is there a way, other than having a new instance of KafkaServer for every test, to remove the existing messages at the end of each test or to only consume the messages I'm interested in in the current test ?

**Comment by simonsouter** [comment]
Hi,

Probably best to use the same KafkaServer within a suite as it does take a while to startup.  Indeed there are some tricky issues with Kafka around starting consumption at the right point in a test setup.  I remember having the same type of issues when we first created the Testkit.  I would suggest you check out some of our unit tests for examples: https://github.com/cakesolutions/scala-kafka-client/tree/master/akka/src/test/scala/cakesolutions/kafka/akka.

We usually create a random topic for each test in a suite for isolation to avoid the issue you mention and also use OffsetResetStrategy.EARLIEST on the consumer to make sure we pick up all messages a test producer delivered.

Hope that helps.

**Comment by dmartindelorme** [comment]
Thanks I hadn't thought about a random topic for each test.

I wonder however how that suite can pass [https://github.com/cakesolutions/scala-kafka-client/blob/master/akka/src/test/scala/cakesolutions/kafka/akka/KafkaProducerActorSpec.scala](https://github.com/cakesolutions/scala-kafka-client/blob/master/akka/src/test/scala/cakesolutions/kafka/akka/KafkaProducerActorSpec.scala) since the topic is the same in both tests and the kafka server is the same also ? How come the second consume call doesn't fail because of the 3 previous messages ?

**Comment by jkpl** [comment]
Good catch! Both tests write the same data and read all the way from the beginning, which is why they both pass.

**Comment by dmartindelorme** [comment]
Even if it will surely work, having to use random topics in an app with fixed topic titles seems to be a pain to implement in a test environment.

I'm wondering if the best solution wouldn't be just to implement a publicly accessible function to delete the log file after each test as it's done here : [https://github.com/cakesolutions/scala-kafka-client/blob/master/testkit/src/main/scala/cakesolutions.kafka/testkit/KafkaServer.scala#L121](https://github.com/cakesolutions/scala-kafka-client/blob/master/testkit/src/main/scala/cakesolutions.kafka/testkit/KafkaServer.scala#L121). That way we can re-use the same server throughout the suite and juste delete the log file after each test. What do you think ?

**Comment by simonsouter** [comment]
I would not expect you to be able to use the same KafkaServer after deleting the log file.

I updated the test you referenced to use random topics: https://github.com/cakesolutions/scala-kafka-client/pull/86

BTW in the future Kafka will provide an admin api which would allow us to programatically delete topics:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-4+-+Command+line+and+centralized+administrative+operations

**Comment by dmartindelorme** [comment]
Ok so when this feature is complete, the best way will be to delete the fixed topic after each test ?
