### ISSUE TITLE
When send the message using ASK pattern, Timeout exception throw. 

### ISSUE THREAD

**Issue by harmeetsingh0013** [cakesolutions/scala-kafka-client#97]
I am using cake solution Akka client for scala and Kafka. While I am creating a KafkaProducerActor actor and trying to send message using ask pattern and return future and perform some operations, but every time, I am facing ask timeout exception. For more details, please visit on http://stackoverflow.com/questions/42188622/apache-kafka-kafkaproduceractor-throws-exception-ask-timeout this link.

**Comment by jkpl** [comment]
Hiya, I posted [an answer on StackOverflow](http://stackoverflow.com/a/42232671/6665061). Let's continue the discussion there.
