### ISSUE TITLE
actors fail to terminate

### ISSUE THREAD

**Issue by 123avi** [cakesolutions/scala-kafka-client#99]
Hi, 
I am working on example project using scala-kafka-client (planning to submit it as activator template).
I am integrating with akka actors but It seems that the actors fail to terminate.
you can checkout [this project ](https://github.com/123avi/kafka-akka-example) (would love to get your feedback). Running the [PingPongActorSpec](https://github.com/123avi/kafka-akka-example/blob/master/src/test/scala/com/example/PingPongActorSpec.scala) test you can see that the actors fail to terminate : 

> [WARN] [03/02/2017 08:22:03.141] [ScalaTest-run] [akka.actor.ActorSystemImpl(MySpec)] Failed to stop [MySpec] within [10 seconds] 
> -> / LocalActorRefProvider$$anon$1 class akka.actor.LocalActorRefProvider$Guardian status=0 2 children
>    ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 5 children
>    |   ⌊-> deadLetterListener RepointableActorRef class akka.event.DeadLetterListener status=0 no children
>    |   ⌊-> eventStreamUnsubscriber-1 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children
>    |   ⌊-> log1-Logging$DefaultLogger RepointableActorRef class akka.event.Logging$DefaultLogger status=0 no children
>    |   ⌊-> testActor1 RepointableActorRef class akka.testkit.TestActor status=0 no children
>    |   ⌊-> testActor2 RepointableActorRef class akka.testkit.TestActor status=0 no children
>    ⌊-> user LocalActorRef class akka.actor.LocalActorRefProvider$Guardian status=4 Terminating(Termination)
>        |    toDie: Actor[akka://MySpec/user/PongTest#1896611585]
>        ⌊-> PongTest RepointableActorRef class com.example.PongActor status=4 Terminating(Termination)
>            |    toDie: Actor[akka://MySpec/user/PongTest/PingKafkaConsumerActor#-1239449583]
>            ⌊-> PingKafkaConsumerActor LocalActorRef class cakesolutions.kafka.akka.KafkaConsumerActorImpl status=2 no children
>

**Comment by jkpl** [comment]
Hi @123avi!

We've seen other projects using scala-kafka-client having similar kind of problems in the past, but so far we haven't been able to reproduce the problem ourselves.

We'll look into to your example soon. Thanks for reporting this!

**Comment by simonsouter** [comment]
This test appeared to pass for me, are you still seeing this?

**Comment by 123avi** [comment]
Hi @simonsouter thanks for looking into it, the problem is not if the test pass or not but the ActorSystem is not terminated (as you can see at the log above) .
also if you check the application main you will see that the "PingActor" never terminates even after PoisnPill ( nor context.stop(self) )

**Comment by 123avi** [comment]
@simonsouter , @jkpl it seems that the problem is with the testkit.KafkaServer, it holds the actor system from terminating gracefully.

**Comment by simonsouter** [comment]
Hi @123avi,

I took a look at your test (PingPongActorSpec).

1: You are not terminating the PongActor, i think this is causing the ActorSystem to fail to stop.  I added "pongActor ! PoisonPill" to line 53 and the actor system seems to shutdown ok.
2: In ping and pong actors, you dont need to do "kafkaConsumerActor ! Unsubscribe" in the postStop hook.  The KafkaConsumerActor will shutdown itself when it observes you actors death.

**Comment by 123avi** [comment]
thank @simonsouter , I agree that terminating the actor explicitly will do it, but this line should do the termination gracefully of the Actor System. 
`TestKit.shutdownActorSystem(system)`
(as you can see [here](https://github.com/123avi/SimpleAkkaPingPong) for example)

**Comment by simonsouter** [comment]
Ok, i think i figured it out.  Seems like calling close() on the underlying Kafka producer blocks indefinitely when Kafka has already been shut down.  It will be easy to fix this.  

Thanks for helping to track this one down.

**Comment by 123avi** [comment]
Awesome. thanks

**Comment by simonsouter** [comment]
Cant fix due to bugs in the underlying Kafka driver: https://issues.apache.org/jira/browse/KAFKA-1894

There is a deadlock situation in the Kafka driver when connection to the Kafka server is lost prior to an attempt to shutdown the actor system.

**Comment by 123avi** [comment]
@simonsouter 
as a workaround I simply terminate the actor system before shutting down kafka server.
I understand that there is a blocking loop. 
 can't the kafka server hold it's shutdown and/or retry periodically till the actorsystem shuts down ?

**Comment by kufi** [comment]
Just ran into that same problem.

You could unblock the loop with the hint from the following comment: https://issues.apache.org/jira/browse/KAFKA-1894?focusedCommentId=15036256&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15036256

This could be used as sort of "last resort", to kill a blocking subscriber.
